---
title: "ROC_Curve"
author: "David Padrino"
date: "May 16, 2016"
output: html_document
---
# Generacion de Curva ROC

### Carga de Bibliotecas
```{r}
library("zoo")
```

### Casos de Prueba
```{r}
real = c(2, 2, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1)
scores = c(0.9, 0.8, 0.7, 0.6, 0.55, 0.54, 0.53, 0.52, 0.5, 0.5, 0.5, 0.5, 0.38, 0.37, 0.36, 0.35, 0.34, 0.33, 0.30, 0.1)
target = 2


real2 = c(2, 2, 1, 2, 3, 2, 3, 1, 2, 1, 2, 1, 2, 1, 3, 1, 2, 1, 3, 3)
scores2 =c(0.9, 0.8, 0.7, 0.6, 0.55, 0.54, 0.53, 0.52, 0.5, 0.5, 0.5, 0.5, 0.38, 0.37, 0.36, 0.35, 0.34, 0.33, 0.30, 0.1)
target2 = 3
```


### Funciones de Interes (_graphics_ Para graficar y _generate_ROC_ para generar la curva y calcular AUC)
```{r}
graphics <- function(scores, real, target){
  ToX <- as.numeric()
  ToY <- as.numeric()
  PrevScore <- 99999999999999999999
  i <- 1
  area <-0
  PosVal <- NegVal <- 0
  PrevPosVal <- PrevNegVal <- 0
  Pos.Len <- length(real[real %in% target])
  Neg.Len <- length(real) - Pos.Len
  while (i <= length(scores)){
    if(scores[i] != PrevScore){
      ToX <- append(ToX, PosVal / Pos.Len)
      ToY <- append(ToY, NegVal / Neg.Len)
      PrevScore <- scores[i]
      PrevPosVal <- PosVal
      PrevNegVal <- NegVal
    }
    if (real[i] == target){
      PosVal <- PosVal + 1
    }else{
      NegVal <- NegVal + 1
    }
    i <- i+1  
  }
  # The last point ins't ploted, this lines below are necessary
  ToY <- append(ToY, 1)
  ToX <- append(ToX, 1)
  auc <- sum(diff(ToY)*rollmean(ToX,2)) # To calculate the AUC of the ROC curve
  plot(ToY, ToX, xlim=c(0, 1), ylim=c(0, 1), type = "l", main = "Curva ROC", xlab = "Falso Positivo", ylab = "Verdadero Positivo")
  legend(0.5,0.3, paste("ROC (AUC) =", auc), col = c(3), lty = c(2), pch = c(NA))  
  abline(0,1, lty = 2)
  points(ToY, ToX, col = 2, pch = "o") 
  lab <- c("inf")
  lab <- append(lab,sort(unique(scores), decreasing = T))
  text(ToY, ToX, labels=lab, cex= 0.7, pos = 2)
}  


generate_ROC <- function(scores, real, target){
  # Generate ROC curve
  ## In number of classes is less-equal than 2
  if (length(unique(real)) <= 2){
    # just 4 2 classes
    scores.real <- data.frame(scores,real)
    scores.real <- scores.real[with(scores.real, order(-scores)),]
    graphics(scores.real$scores, scores.real$real, target)   
  }else{
  ## #classes greater than 2
    all.classes <- unique(real)
    all.classes <- all.classes[-target]
    i <- 1
    while (i <= length(all.classes)) {
      scores.real <- data.frame(scores,real)       
      scores.real <- scores.real[!scores.real$real == all.classes[i],]
      scores.real <- scores.real[with(scores.real, order(-scores)),]
      graphics(scores.real$scores, scores.real$real, target)
      i <- i+1
    }
  } 
}
    


```


### Casos de ejemplo de la curva
El primero con 2 clases, el segundo con 3.
```{r}
generate_ROC(scores, real, target)
generate_ROC(scores2, real2, target2)

```

